---
- name: acquire build dependencies
  apt:
    name: "{{ item }}"
    state: latest
  when: "{{ ansible_os_family == 'Debian' }}"
  with_items:
  - mercurial
  - automake
  - autoconf
  - gcc
  - dovecot-dev
  - build-essential

- name: clone antispam
  git:
    repo: https://github.com/horazont/dovecot-antispam-plugin
    version: feature/imapflags
    dest: /opt/dovecot-antispam

- name: autogen
  command: ./autogen.sh
  args:
    chdir: /opt/dovecot-antispam

- name: configure
  command: ./configure --prefix=/usr --libdir=/usr/lib --with-dovecot=/usr/lib/dovecot/
  args:
    chdir: /opt/dovecot-antispam

- name: clean after dovecot update
  command: make clean
  when: "{{ (dovecot_updated_deb | default({}) | changed) or (force_dovecot_rebuild | default(False)) }}"
  args:
    chdir: /opt/dovecot-antispam

- name: compile
  command: make
  args:
    chdir: /opt/dovecot-antispam

- name: install
  command: make install
  args:
    chdir: /opt/dovecot-antispam
  notify:
  - restart dovecot
