---
- name: "imap: deploy ferm file"
  template:
    src: ferm/imap.conf
    dest: /etc/ferm/ferm.d/40-dovecot-imap.conf
    owner: root
    group: root
  notify: run ferm

- name: "managesieve: deploy ferm file"
  template:
    src: ferm/managesieve.conf
    dest: /etc/ferm/ferm.d/40-dovecot-manageseive.conf
    owner: root
    group: root
  notify: run ferm
  when: "{{ dovecot_managesieve }}"

- name: "replication: deploy ferm file"
  template:
    src: ferm/replication.conf
    dest: /etc/ferm/ferm.d/50-dovecot-replication.conf
    owner: root
    group: root
  notify: run ferm
  when: "{{ dovecot_replication }}"
