---
- name: dovecot pin
  template:
    src: pin-dovecot.pref
    dest: /etc/apt/preferences.d/
  register: pinning
  tags:
  - dovecot

- name: install dovecot (debian)
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: "{{ 'yes' if (pinning | changed | default(False)) else 'no' }}"
  with_items:
  - dovecot-core
  - dovecot-imapd
  - dovecot-sieve
  - dovecot-managesieved
  - dovecot-ldap
  - dovecot-lmtpd
  tags:
  - dovecot
  register: dovecot_updated_deb

- name: create vmail group
  group:
    name: vmail
    state: present
    system: yes
  tags:
  - dovecot

- name: create vmail user
  user:
    createhome: no
    name: vmail
    system: yes
    group: mail
    groups: mail
    shell: /sbin/nologin
    state: present
  tags:
  - dovecot

- name: configure dovecot
  template:
    src: dovecot/dovecot.conf
    dest: /etc/dovecot/dovecot.conf
    owner: dovecot
    group: dovecot
    mode: ugo=r
  tags:
  - dovecot
  notify:
  - restart dovecot

- name: configure ldap dbs
  template:
    src: dovecot/dovecot-userdb-ldap.conf
    dest: "{{ item.file }}"
    owner: dovecot
    group: dovecot
    mode: ugo=r
  with_items: "{{ dovecot_userdb + dovecot_passdb }}"
  when: item.driver == "ldap"
  tags:
  - dovecot
  notify:
  - restart dovecot

- name: upload certificate
  copy:
    content: "{{ dovecot_tls_cert }}"
    dest: /etc/dovecot/ssl.crt
    owner: root
    group: root
    mode: ugo=r
  when: "{{ not dovecot_tls_cert_file }}"
  tags:
  - dovecot
  - certificate
  notify:
  - restart dovecot

- name: link certificate
  file:
    state: link
    src: "{{ dovecot_tls_cert_file }}"
    dest: /etc/dovecot/ssl.crt
    owner: root
    group: root
    mode: u=r,go-rwx
    force: yes
  when: "{{ not not dovecot_tls_cert_file }}"
  tags:
  - dovecot
  - certificate
  notify:
  - restart dovecot

- name: upload key
  copy:
    content: "{{ dovecot_tls_key }}"
    dest: /etc/dovecot/ssl.key
    owner: root
    group: root
    mode: u=r,go-rwx
  when: "{{ not dovecot_tls_key_file }}"
  tags:
  - dovecot
  - certificate
  notify:
  - restart dovecot

- name: link key
  file:
    state: link
    src: "{{ dovecot_tls_key_file }}"
    dest: /etc/dovecot/ssl.key
    owner: root
    group: root
    mode: u=r,go-rwx
    force: yes
  when: "{{ not not dovecot_tls_key_file }}"
  tags:
  - dovecot
  - certificate
  notify:
  - restart dovecot

- include: dovecot-ferm.yml
  when: ferm
  tags:
  - dovecot
  - ferm

- include: sieve.yml
  when: dovecot_sieve
  tags:
  - dovecot
  - dovecot-sieve

- include: antispam.yml
  when: dovecot_antispam
  tags:
  - dovecot
  - dovecot-antispam
