---
- name: create global sieve directories
  file:
    path: "/usr/local/share/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,go=rx
  with_items:
  - sieve
  - imapsieve

- name: deploy global sieve scripts
  copy:
    src: "sieve/{{ item }}"
    dest: /usr/local/share/sieve/
    owner: root
    group: root
    mode: u=rw,go=r
  register: sieve_scripts
  with_items:
  - file-spam-into-junk.sieve
  - flag-spam-as-junk.sieve
  - default.sieve

- name: compile global sieve scripts
  command:
  args:
    argv:
    - sievec
    - "-c"
    - "/etc/dovecot/dovecot.conf"
    - "/usr/local/share/sieve/{{ item.item }}"
  with_items: "{{ sieve_scripts.results }}"

- name: create pipe script directory
  file:
    state: directory
    recurse: true
    path: /usr/local/lib/dovecot/sieve
    mode: u=rwx,go=rx
    owner: root
    group: root
